const PRODUCTS=[
{id:'frame',name:'The Memory Frame',price:899,cat:'Physical',tag:'BESTSELLER',desc:'Turn one unforgettable photograph into something they can keep close.',img:'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=900&q=88'},
{id:'album',name:'The Story Book',price:1499,cat:'Physical',tag:'NEW',desc:'A handcrafted collection of the moments that made your story.',img:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=900&q=88'},
{id:'box',name:'The Memory Box',price:1299,cat:'Physical',tag:'MOST LOVED',desc:'A keepsake box filled with photographs, notes and little surprises.',img:'https://images.unsplash.com/photo-1513883049090-d0b7439799bf?auto=format&fit=crop&w=900&q=88'},
{id:'digital',name:'A Letter, Reimagined',price:399,cat:'Digital',tag:'DIGITAL',desc:'An interactive digital surprise made around your person and your story.',img:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=88'},
{id:'story',name:'Our Story — Interactive',price:699,cat:'Digital',tag:'DIGITAL',desc:'A beautiful scroll-through memory experience they can open anywhere.',img:'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=900&q=88'},
{id:'digital-video',name:'Our Moments — Video Story',price:899,cat:'Digital',tag:'DIGITAL',desc:'A cinematic digital story built from your favourite memories, music and messages.',img:'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=88'},
{id:'digital-card',name:'The Digital Love Card',price:299,cat:'Digital',tag:'DIGITAL',desc:'A beautifully animated card with your words, photos and a private shareable link.',img:'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=900&q=88'},
{id:'digital-timeline',name:'Our Timeline',price:599,cat:'Digital',tag:'DIGITAL',desc:'A personalised timeline of the little moments that became your favourite memories.',img:'https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=900&q=88'},
{id:'surprise',name:'The Birthday Reveal',price:2499,cat:'Experience',tag:'EXPERIENCE',desc:'We plan, style and deliver a surprise around the person you love.',img:'https://images.unsplash.com/photo-1464349153735-7db50ed83c84?auto=format&fit=crop&w=900&q=88'},
{id:'anniversary',name:'The Anniversary Moment',price:2999,cat:'Experience',tag:'EXPERIENCE',desc:'A thoughtful anniversary setup designed to feel deeply personal.',img:'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=88'},
{id:'surprise-proposal',name:'The Proposal Reveal',price:4999,cat:'Experience',tag:'EXPERIENCE',desc:'A beautifully planned proposal setup with styling, details and a memorable reveal.',img:'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=900&q=88'},
{id:'surprise-baby',name:'First Birthday Magic',price:3499,cat:'Experience',tag:'EXPERIENCE',desc:'A joyful first-birthday surprise planned around the little one and the family.',img:'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=900&q=88'},
{id:'surprise-memory',name:'Memory Trail',price:2799,cat:'Experience',tag:'EXPERIENCE',desc:'A clue-led surprise journey with meaningful stops, notes and a final reveal.',img:'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=900&q=88'},
{id:'custom',name:'Made For Them',price:999,cat:'Custom',tag:'CUSTOM',desc:'Tell our studio your idea and we will turn it into a one-of-one gift.',img:'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?auto=format&fit=crop&w=900&q=88'}
];
let cart=JSON.parse(localStorage.getItem('dudegifts-cart')||'[]');
const money=n=>'₹'+n.toLocaleString('en-IN');
function save(){localStorage.setItem('dudegifts-cart',JSON.stringify(cart));updateBag()}
function updateBag(){document.querySelectorAll('.bag-count').forEach(x=>x.textContent=cart.reduce((a,b)=>a+b.qty,0))}
function showCartSuccess(name){
 const toast=document.querySelector('.cart-success-toast')||(()=>{const t=document.createElement('div');t.className='cart-success-toast';t.innerHTML='<span class=\"toast-check\">✓</span><span><strong>Added to cart successfully</strong><small></small></span>';document.body.appendChild(t);return t})();
 toast.querySelector('small').textContent=name+' is now in your Gift Box.';
 toast.classList.remove('show');void toast.offsetWidth;toast.classList.add('show');
 clearTimeout(window.__cartToastTimer);window.__cartToastTimer=setTimeout(()=>toast.classList.remove('show'),3200);
}
function add(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const found=cart.find(x=>x.id===id);found?found.qty++:cart.push({...p,qty:1});save();showCartSuccess(p.name);const btn=document.querySelector('#product-modal.open .product-details .btn-primary');if(btn){const original=btn.textContent;btn.textContent='ADDED TO GIFT BOX ✓';btn.classList.add('added');setTimeout(()=>{if(btn.isConnected){btn.textContent=original;btn.classList.remove('added')}},2200)}openBag()}
function change(id,d){const x=cart.find(a=>a.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(a=>a.id!==id);save();renderBag()}
function remove(id){cart=cart.filter(a=>a.id!==id);save();renderBag();if(typeof window.renderFullCart==='function')window.renderFullCart()}
function renderBag(){const box=document.querySelector('.drawer-items');if(!box)return;if(!cart.length){box.innerHTML='<div class="empty"><div style="font:600 32px Playfair Display;margin-bottom:8px">Your gift box is waiting.</div><div>Find something made for their story.</div></div>';document.querySelector('.drawer-total').textContent=money(0);return}box.innerHTML=cart.map(x=>`<div class="cart-item"><img src="${x.img}" alt=""><div><h4>${x.name}</h4><small>${money(x.price)} · Qty ${x.qty}</small><div class="qty" style="margin-top:10px"><button onclick="change('${x.id}',-1)">−</button><span>${x.qty}</span><button onclick="change('${x.id}',1)">+</button></div><button class="remove-item" onclick="remove('${x.id}')">Remove</button></div><strong>${money(x.price*x.qty)}</strong></div>`).join('');document.querySelector('.drawer-total').textContent=money(cart.reduce((a,b)=>a+b.price*b.qty,0))}
function openBag(){document.querySelector('.drawer')?.classList.add('open');renderBag()}
function closeBag(){document.querySelector('.drawer')?.classList.remove('open')}
function productCard(p){return `<article class="product-card"><a class="product-open-link" data-product-id="${p.id}" href="product.html?id=${p.id}"><div class="product-image"><img src="${p.img}" alt="${p.name}"><span class="badge">${p.tag}</span><button class="wish" onclick="event.preventDefault();this.textContent=this.textContent==='♡'?'♥':'♡'">♡</button></div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="price">${money(p.price)}</div></div></a></article>`}
function initShop(){const grid=document.querySelector('.shop-grid');if(!grid)return;let list=[...PRODUCTS];const render=()=>grid.innerHTML=list.map(productCard).join('');const applyFilter=c=>{document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.cat===c));document.querySelectorAll('[data-shop-category]').forEach(x=>x.classList.toggle('active-category',x.dataset.shopCategory===c));list=c==='All'?[...PRODUCTS]:PRODUCTS.filter(p=>p.cat===c);render();document.querySelector('#collection')?.scrollIntoView({behavior:'smooth',block:'start'})};render();document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>applyFilter(b.dataset.cat));document.querySelectorAll('[data-shop-category]').forEach(b=>b.onclick=e=>{e.preventDefault();applyFilter(b.dataset.shopCategory)});document.querySelector('#sort')?.addEventListener('change',e=>{list.sort((a,b)=>e.target.value==='low'?a.price-b.price:e.target.value==='high'?b.price-a.price:a.name.localeCompare(b.name));render()})}
function productMarkup(p,modal=false){return `<div class="product-gallery"><div class="gallery-main"><img src="${p.img}" alt="${p.name}"></div></div><div class="product-details"><div class="eyebrow">${p.cat} · ${p.tag}</div><h1>${p.name}</h1><p class="desc">${p.desc} Designed in the DudeGifts Memory Atelier, with thoughtful details that make the gift feel personal.</p><div class="product-price">${money(p.price)}</div><div class="option"><label>Gift message</label><textarea class="product-message" style="width:100%;min-height:100px;border:1px solid var(--line);background:transparent;padding:13px" placeholder="Write something only they would understand..."></textarea></div><div class="option"><label>Quantity</label><div class="qty"><button onclick="this.nextElementSibling.textContent=Math.max(1,+this.nextElementSibling.textContent-1)">−</button><span>1</span><button onclick="this.previousElementSibling.textContent=+this.previousElementSibling.textContent+1">+</button></div></div><button class="btn btn-primary wide" onclick="add('${p.id}')">ADD TO GIFT BOX →</button><div class="product-notes"><div class="note"><b>DESIGN PREVIEW</b>We check your personalization.</div><div class="note"><b>PACKED WITH CARE</b>Protected for a beautiful arrival.</div><div class="note"><b>NO LOGIN</b>Order simply, without an account.</div></div></div>`}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0];let modal=document.querySelector('#product-modal');if(!modal){modal=document.createElement('div');modal.id='product-modal';modal.className='product-modal';modal.innerHTML='<div class="product-modal-bg" data-product-close></div><section class="product-modal-panel" role="dialog" aria-modal="true" aria-label="Product details"><button class="product-modal-close" data-product-close aria-label="Close product">×</button><div class="product-page product-modal-content"></div></section>';document.body.appendChild(modal);modal.querySelectorAll('[data-product-close]').forEach(x=>x.addEventListener('click',closeProduct));}modal.querySelector('.product-modal-content').innerHTML=productMarkup(p,true);modal.classList.add('open');document.body.classList.add('product-modal-open')}
function closeProduct(){const modal=document.querySelector('#product-modal');if(!modal)return;modal.classList.remove('open');document.body.classList.remove('product-modal-open')}
function initProduct(){const mount=document.querySelector('#product');if(!mount)return;const id=new URLSearchParams(location.search).get('id')||'frame';const p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0];mount.innerHTML=productMarkup(p,false)}
function searchProducts(q){const box=document.querySelector('#search-results');if(!box)return;const results=PRODUCTS.filter(p=>(p.name+p.desc+p.cat).toLowerCase().includes(q.toLowerCase()));box.innerHTML=results.length?results.map(productCard).join(''):'<p style="color:var(--muted)">Nothing found yet. Try “frame”, “digital” or “birthday”.</p>'}
function initActiveNav(){
 const file=location.pathname.split('/').pop()||'index.html';
 const map={
  'gifts.html':'gifts.html',
  'digital-gifts.html':'digital-gifts.html',
  'surprise-events.html':'surprise-events.html',
  'custom-gift.html':'custom-gift.html',
  'about.html':'about.html',
  'contact.html':'contact.html'
 };
 document.querySelectorAll('.nav-links a, .mobile-nav a').forEach(a=>{
  const href=(a.getAttribute('href')||'').split('#')[0];
  const active=map[file] && href===map[file];
  a.classList.toggle('active',!!active);
  if(active) a.setAttribute('aria-current','page'); else a.removeAttribute('aria-current');
 });
}
function init(){updateBag();initActiveNav();document.addEventListener('click',e=>{const link=e.target.closest('.product-open-link');if(link){e.preventDefault();openProduct(link.dataset.productId)}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProduct()});document.querySelectorAll('[data-open-bag]').forEach(x=>x.onclick=openBag);document.querySelectorAll('[data-close-bag]').forEach(x=>x.onclick=closeBag);document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('.mobile-nav')?.classList.toggle('open'));document.querySelector('#search')?.addEventListener('input',e=>searchProducts(e.target.value));initShop();initProduct();document.querySelector('#order-form')?.addEventListener('submit',e=>{e.preventDefault();document.querySelector('.success').style.display='block';e.target.reset()});document.querySelector('#whatsapp')?.addEventListener('click',()=>{const total=cart.reduce((a,b)=>a+b.price*b.qty,0);const text=cart.map(x=>`${x.name} x${x.qty}`).join(', ');location.href=`https://wa.me/919999999999?text=${encodeURIComponent('DudeGifts order: '+text+' | Total '+money(total))}`})}
document.addEventListener('DOMContentLoaded',init);
